### PR TITLE
Create introducting-team-melbourne.jpg

### PR DESCRIPTION
**Pull request by cyberkoi**
team melbourne

### CODE REVIEW

**Comment by carpodaster** [comment]
I think it's a photoshop-job! :wink:

**Comment by anikalindtner** [comment]
SOOOO sweet! I can't even... :heart_eyes_cat:

**Comment by alicetragedy** [comment]
:heart:

**Comment by alicetragedy** [comment]
fyi @snjqi188 I have just renamed the image (there was a minor typo). But all is good on our front. Excited to have your post published this weekend, and we all love your amazing team picture :sparkles:

**Pull request merged**
