### PR TITLE
Team Exercistas Introduction Blog Post

### PR DESCRIPTION
**Pull request by mixolidia**
Hi,

Here is our blog post. 

Thanks!

### CODE REVIEW

**Comment by alicetragedy** [comment]
@mixolidia thank you so much for your contribution – love the pictures :)
I've made a comment directly on the post with what needs changing/adding, but we can publish after that. yay! :space_invader:

**Comment by mixolidia** [comment]
Hi @alicetragedy 
Thanks! I updated the path and added image sources. Publish away. 😃

**Comment by alicetragedy** [comment]
Great! thank you so much @mixolidia – the post is published. 
Congratulations on your first successful pull request to the `summer-of-code`! :sparkles:

**Comment by mixolidia** [comment]
😄 Thanks @alicetragedy!

**Pull request merged**
