### PR TITLE
[WIP] starts creation of HOF for issue #167

### PR DESCRIPTION
**Pull request by sareg0**
Hey there @alicetragedy this is just the humble beginnings of the Hall of Fame page.

I have been trying to reuse as many elements as possible for now.

I also went with a look that was similiar to the sponsor footer, as the hover over of the teasers on the front page was a bit janky and didn't look so great to show the company description on hover.

Perhaps what I could trouble you to do is figure out what content should be there; particularly the special moments part of the page. 

I can take the sponsor info from the sponsor blurbs, and also the teams from the teams app, but the special moments is something I don't have a firm grasp on. I am guessing this could also involve @anikalindtner as she was there.

### CODE REVIEW

**Comment by alicetragedy** [comment]
Awesome, thanks @sareg0. I should have some time tonight to take a look at it for possible suggestions.. and I will also put together a list of things to add to the "Special Moments". thank you for doing this!

**Comment by sareg0** [comment]
heheh it's veerrrrrrrryy basic so far.

**Comment by alicetragedy** [comment]
I've made some comments already. 
For the special moments I'd love to have a grid as well, could you add a mock one for now? each part will probably have a photo with a bit of text, you could fill with one or two paragraphs of Lorem Ipsum text for now? A 3-column row (more or less aligned with the sponsor logos) should work, I think. Let me know if you need any help!
In the meanwhile I will prepare the content.

**Comment by sareg0** [comment]
okey dokey, I'll be doing some work on this this evening.

**Comment by alicetragedy** [comment]
:+1: hit me up if you need any suggestions or want to pair, I'll be around! :tada:

**Comment by sareg0** [comment]
okay, I got the table in... The whole page still needs some layout work, but maybe it's taking more shape now :)

Still working on the headers and such. Trying to make sure not to inject too much custom stuff, but use wha's already there, hence the measured styling choices I have been making :)

**Comment by alicetragedy** [comment]
Hey @sareg0, since this is quite old and there's been quite a few changes on the page since then, is it okay if I close this? We'll be starting fresh this or next month and it might be easier than building on top of this outdated PR.

**Pull request closed without merging**
