### PR TITLE
Add images & links to R'n'B introduction blog post

### PR DESCRIPTION
**Pull request by 1000miles**
Hi @alicetragedy,

as bespoken here are the images of all R'n'B team members. :) Thank you. 

Have a nice evening! 

Thuy 
- on behalf of rubyandbugs -

### CODE REVIEW

**Comment by alicetragedy** [comment]
@1000miles thank you for the PR! I can't merge the pull request because of a merge conflict – I'm not exactly sure what the problem is, but maybe you didn't have the latest changes on your fork and your local copy is out of sync with the `summer-of-code`? See here: https://help.github.com/articles/syncing-a-fork/
could you check if that's the case?

**Comment by 1000miles** [comment]
@alicetragedy oops. i am sorry. i will check this tomorrow. thanks for the hint. :)

**Comment by alicetragedy** [comment]
sure, don't worry about it! just wanted to let you know so you can take a look whenever you have time. :crescent_moon:

**Comment by 1000miles** [comment]
@alicetragedy can you please check, if everything is okay now? thank you.

**Comment by alicetragedy** [comment]
hey this looks good! :+1: 
the only problem is that the metadata at the top unfortunately does not allow for any markup, but I will fix that myself after merging. Thanks for fixing the merge locally!

**Pull request merged**
