### PR TITLE
#179 - More consistent hierarchy

### PR DESCRIPTION
**Pull request by troubalex**
First round of changes on the inner pages:
- more consisten use of headlines
- font sizes are now based on a scale
- some minor changes to white space

### CODE REVIEW

**Comment by troubalex** [comment]
Sponsorship packages is in the middle of a rework, and hence broken. I meant to not commit that, but.. oh well... 🙈

**Comment by troubalex** [comment]
I believe this part is done. Please merge if you're happy, otherwise LMK what I missed. 😸

**Comment by alicetragedy** [comment]
This looks good! There's only a small glitch with the container width on the press page, I believe that removing the extra `section`, `div` and `article` tags, which are pretty useless right now anyway, should fix it and clean up the structure of the page. 
Do you have time to fix that @troubalex?

**Comment by troubalex** [comment]
I'll take a look, and see how big of a fix it is. Should be doable, although probably not this week.

**Comment by alicetragedy** [comment]
@troubalex let me know if you don't have time this week, I'm happy to fix it myself after merging this. No biggie! I'm so happy you managed to find some time for it though, it looks sooo much better already ✨

**Pull request merged**
