### PR TITLE
Auto-generate year in sponsorship guidelines

### PR DESCRIPTION
**Pull request by carpodaster**
Alternative solution to #249

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hey @carpodaster, I think this is a great solution! Just one thing I noticed: it should probably not show the current year, but the future year (e.g. right now it should show 2017 instead of 2016). The idea of adding `| plus:'1'` after `date: "%Y"` makes me cringe 🙈  but I don't think there's a better way, or is there?

**Comment by carpodaster** [comment]
@alicetragedy Ah, I completely forgot about the fact that it should be "season-aware". That makes it a lot more complicated. E.g. the first 5 months of a year it should be the current year while it should be the folllwing year after the summer has started. I'm not sure if that is possible with static pages + some liquid voodoo.

**Comment by carpodaster** [comment]
@alicetragedy I've managed to hack the season-awareness into the template but it ain't pretty. Shall we roll with it? Or shall we just close this PR?

**Comment by alicetragedy** [comment]
@carpodaster I'm just gonna cover my eyes and merge 🙈

**Pull request merged**
