### PR TITLE
Improve blog post creation instructions in README

### PR DESCRIPTION
**Pull request by carpodaster**

### CODE REVIEW

**Comment by alicetragedy** [comment]
I'll take a look at this tonight – was actually working on that this week/weekend, but glad one part is finally out there ;) I'll see if there are any additions from my side! :+1:

**Comment by carpodaster** [comment]
Very cool, @alicetragedy, thanks for writing down the forking-procedure. :pencil2: Are we good to merge then?

**Comment by alicetragedy** [comment]
@carpodaster so, I've made some changes and added a link to the forking docs. Feel free to add or remove or comment on things! I was just getting frustrated with having to explain the process for every single PR we got so far for the blog posts ;)

**Comment by alicetragedy** [comment]
@carpodaster re:merge – yes, I think so, unless you have any objections! MERGE ALL THE THINGS

**Comment by carpodaster** [comment]
#yolo :)

**Comment by alicetragedy** [comment]
:tada: :confetti_ball: :sparkles: I'm so relieved this is merged! thank you for sticking with my ramble-ey comments :+1:

**Comment by anikalindtner** [comment]
\o/\o/\o/

**Pull request merged**
