### PR TITLE
Responsive things, should close #65

### LINKED ISSUE #65: mobile improvements
So I took a look at the site on a tablet, and here are a few things we could still improve.

These are all minor things, but worth fixing eventually.

image-2
- The burger menu has no margin or padding at the top, it makes it look very weird. 
- The progress bar needs fixing on mobile, as it doesn't show all icons.

image-1
- When the sponsor packages are stacked, there is no space between the top and the bottom one.

image

+ [ ] The donate button is way bigger than necessary in the page views. This is from the application guide, it comes from the sidebar and could probably also be hidden.
+ [ ] Not sure if we need all the sidebar links at the bottom of each page; in theory we can access everything through the top menu.
+ [ ] Which brings me to the next point: why not make a sticky menu at the top? It's not so bad on tablet, but on a mobile phone you have to do A LOT of scrolling if you have to get back up and navigate to another page.

### PR DESCRIPTION
**Pull request by lislis**
This should address everything in the said issue
ᕕ( ᐛ )ᕗ

### CODE REVIEW

**Comment by alicetragedy** [comment]
:tada:

**Comment by sareg0** [comment]
HOLY COWS ON BICYCLES LISA! 
I can't event!

**Comment by carpodaster** [comment]
:confetti_ball: 

Now, can we also make it [WAP](https://en.wikipedia.org/wiki/Wireless_Application_Protocol) compatible? :trollface:

**Comment by lislis** [comment]
@carpodaster haha, nope ;)

**Pull request merged**
