### PR TITLE
Potato code at MirrorConf

### PR DESCRIPTION
**Pull request by Sveijk**
Hi Vaishali!

Here's our blogpost for last Thursdays visit to Braga Portugal where we spoke at MirrorConf.  
Let me know if changes need to be made.

Best regards🙋‍♀️ Sabine
@nerdyvaishali

### CODE REVIEW

**Comment by v-thakkar** [comment]
Hi @Sveijk ! Your PR contains your last student blogpost as well. Can you please remove them and extra images [if there are any]? I think you intend to send this PR for the conference blogpost only.

**Comment by Sveijk** [comment]
@nerdyvaishali 

Hi Vaishali! I removed the previous blogpost from this PR. Deleted the file. Best regards 🙋‍♀️

**Comment by v-thakkar** [comment]
Hi @Sveijk ! Actually you need to push revised commit in the PR which removes that extra file from the PR. Right now what your revised PR does is it actually removes your previous blog post from our repo.

**Comment by Sveijk** [comment]
Hi Vaishali!

Could you help me on this one? I accidentally deleted the branch where our
first blog post was (hurdles of a junior... what a coincidence on that
topic ;-) ). Now everytime I make a new branch and pull it from upstreams
Railsgirls repository towards my repository, push the changes, I don't see
the "hurdles" blogpost, but that still ends up being in the Pull Request I
send to you.

What can I do, or could you help me?

Best regards 🙋‍♀️ Sabine

Op do 1 nov. 2018 om 12:48 schreef vaishali Thakkar <
notifications@github.com>:

**Comment by v-thakkar** [comment]
@Sveijk I'll check more on this Monday but I was wondering if you're creating new branch with a different name? In the worst case scenario, you can also fork our repo again, then push your changes and send a PR to us.

**Pull request closed without merging**
