### PR TITLE
First blog for Team Echo

### PR DESCRIPTION
**Pull request by nanjekyejoannah-zz**
Added content for team Echo's first blog.

### CODE REVIEW

**Comment by klappradla** [comment]
Hey @nanjekyejoannah thanx for your PR!

Alas, there are some difficulties, we cannot merge it like this straight away 😞 
- 592b8aff068ef21c4570ff602757cb21b401d5a6 is an incomplete merge  
  the `+<<<<<<< HEAD` in the first line for instance indicates this. Besides that, this commit also introduces duplicates in the entries in the .yml file - also an indicator that there was a incomplete merge.
- 574905a changes **all** files of the blog... that's too much, it should only add a new one for your post  
  Which editor were you using? Are you by any chance working on windows? If so, see [here](https://help.github.com/articles/dealing-with-line-endings/) for how to deal with this.

It is way more effort to rework this PR (especially if there's a line endings issue) than to just close it and open a new one with just your post. So I'd suggest to do the latter.

To do so, I'd suggest do just start clean again:
1. Fix your editor and line endings issues if there are any
2. Save the `.md` file of your post somewhere (and check for the line endings)
3. Remove your fork of the repo, fork it again and add your changes
4. Before committing your changes, **do a `git pull`** to avoid merge conflicts up front

Then you should end up with **just one commit** which only changes one file (your post) - then create a new PR with this one 🚀

**Comment by michaelem** [comment]
@nanjekyejoannah since @klappradla asked me to help out with an explanation on the line endings thing:
Usually windows uses a different kind of newline (lfrf) than unix systems (lf). Your commits look like your editor or ide enforced the windows-style line endings on the entire project (which uses unix-style endings). There should be a way to configure the line endings used in your editor. If you have any questions on that feel free to ping me!

**Comment by nanjekyejoannah-zz** [comment]
This is noted let me do the changes and commit again.

**Comment by nanjekyejoannah-zz** [comment]
I have decided to do the amendments on my fork directly because I noticed I was getting the same error. Unfortunately I achieved all corrections in 4 commits. Any ideas on how we can squash them into one directly on git hub .

**Comment by klappradla** [comment]
We can squash them once you opened a new PR. Why do you need 4 commits though?

**Pull request closed without merging**
