### PR TITLE
[WIP] Blogbranch

### PR DESCRIPTION
**Pull request by lislis**
I tried the archive gem, but it doesn't seem to work. I guess I'm missing something obvious?

### CODE REVIEW

**Comment by carpodaster** [comment]
@lislis is the archive gem supported by GH pages? I know they have a very strict whitelist of supported jekyll plugins

**Comment by lislis** [comment]
actually good question. I haven't checked but since it's from the official jekyll people I just though it would be supported

**Comment by lislis** [comment]
Bummer, it's not supported :/ Then I can close this PR anyway... Back to the drawing board

**Comment by alicetragedy** [comment]
meh. that sucks :(

**Pull request closed without merging**
