### PR TITLE
Team Melbourne Final Official Post

### PR DESCRIPTION
**Pull request by cyberkoi**
**Infographic**: https://www.dropbox.com/sc/wxeclaqo7uwxamg/AADf-uDgW7qqErkZnlS7p8FWa?dl=1
**SoundCloud Podcast**: `<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/223931295&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>`
**Team Photo**: https://www.dropbox.com/sc/sif1cgp6a4gbb8v/AABDTDo_bm9IRe-AtHbqng9Ta?dl=1
**GIF of Plugin**: https://www.dropbox.com/s/ucg8hkbcr6f5m8c/My%20Edited%20Video%20%282%29.gif?dl=1

### CODE REVIEW

**Comment by cyberkoi** [comment]
RGSoC Orga! Sorry about this, we made a mistake with the infographic - please use this new link instead -> https://www.dropbox.com/sc/v0d7qr7z5rq52fv/AABIqfJh4mvfkFj1RSOWQPiua?dl=1

**Comment by alicetragedy** [comment]
hey @cyberkoi could you add all images to the `img/blog/2015` folder as instructed in the contribution guidelines [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/README.md#images)? That way we don't have problems with image links changing.. 
You can add all the changes to this pull request and I'll make sure to merge after that. Thanks!

**Comment by cyberkoi** [comment]
Done! @alicetragedy. The file I created hasn't appeared in the `/img` folder, but this is the link to view the [3 photos](https://github.com/rails-girls-summer-of-code/summer-of-code/pull/147).
I realize that I probably should have added the jpeg images INTO the file and not commented on it. Please let me know if this is a big issue. :-(

I'm not able to upload the podcast, I hope the iframe link will do.

**Comment by alicetragedy** [comment]
no problem with the podcast @cyberkoi! that's absolutely fine :)

**Pull request merged**
