### PR TITLE
Create Introducing Team GirlsCodersWarsaw

### PR DESCRIPTION
**Pull request by Czarrrna**
We added our introduction.

Team GirlsCodersWarsaw

### CODE REVIEW

**Comment by alicetragedy** [comment]
thank you so much for your pull request @Czarrrna! I really like the photos :)

There are a couple of things we need to change before merging the pull request – could you do the following for me? 
- change date in post heading (see comment)
- change the file name to `2015-07-16-Introducing-Team-GirlsCodersWarsaw.md` (the .md extension is important, it turns it into a Markdown file)
- if you can, please add the images to the folder `img/blog/2015` and link them into your blog post. this will avoid broken images in case the ones you have uploaded on imgur disappear someday! If that's too difficult or confusing, let me know.
- please add photo credits (ie. who took the photo), you can copy the style from the other blog posts / team introductions.

You can make a new commit with the changes, and push to your branch, it will be added to your pull request automatically. Please ask your coaches for help if you have problems, or get in touch with me directly – I'd be happy to help! :)

**Comment by Czarrrna** [comment]
Laura,
I did all the changes that you asked, but I didn't know how to add images
to your directory... So I didn't changed the links in post.
Please help!

2015-07-14 17:35 GMT+02:00 Laura notifications@github.com:

**Comment by alicetragedy** [comment]
Ania,
some of the other teams have "forked" our repo, allowing them to have a copy of the repo locally and to add some files to the `img` folder. However I think in your case, the file was added on GitHub directly (as per our instructions, which were outdated and needed updating!) – so don't worry about it, I will take care of changing it for you after we've merged :)
I can't seem to see your new changes, have you pushed to the branch and/or changed it directly on GitHub.com? (the second might be the easiest to do, as it's only small changes)

Also if you could post here the names of the people the image should be credited to and/or who took the picture, I can add that to the post as well. thank you @Czarrrna!

**Comment by Czarrrna** [comment]
I added the credits. And add a new file. Is it here:
https://github.com/Czarrrna/summer-of-code/blob/gh-pages/blog/_posts/2015-07-16-Introducing-Team-GirlsCodersWarsaw.md

2015-07-15 10:52 GMT+02:00 Laura notifications@github.com:

**Comment by Czarrrna** [comment]
@alicetragedy: As I can see, it is in my directory...? But I couldn't do a pull request.

**Comment by alicetragedy** [comment]
I'm not sure we can merge that in – could you make a pull request from that fork/file? If you navigate to the root of your repo: https://github.com/Czarrrna/summer-of-code, you should see the little green "Compare and Review" Pull request button, as shown [here](https://help.github.com/articles/using-pull-requests/). Did that not work?

**Comment by alicetragedy** [comment]
I know it seems a little complicated, but I'm sure we will figure it out, @Czarrrna ;)

**Comment by Czarrrna** [comment]
@alicetragedy  I guess I did?

**Comment by alicetragedy** [comment]
@Czarrrna Awesome! 
I still need image/credit information (even one of your names is fine) – you can just write it as a comment here, and I can update it after I merge. :+1:

**Comment by Czarrrna** [comment]
Is images credits in my second pull request okay or should I put it here?

**Comment by alicetragedy** [comment]
you're right, I'm sorry! The credits in your second pull request are perfect, nevermind. I don't need anything else from you :)

**Pull request closed without merging**
