### PR TITLE
Adjust font size for blog article body text

### PR DESCRIPTION
**Pull request by alexwllms**
@anikalindtner @lislis @apertoclaudi

I've updated the paragraph and list item font-size to 18px **only** when they appear within an article. 

I'd like these units to be in REM, however Bootstrap is resetting the browser default font-size to 10px so I would have to refactor a few things to get that to work. *Future enhancement.*

Have a look and I'll squash the commits before I merge.

### CODE REVIEW

**Comment by lislis** [comment]
Hey, was there a reason you updated the gemfile.lock? Did something in your configuration not work?

**Comment by alexwllms** [comment]
Hi @lislis Jekyll failed on starting the server. If you think it's a problem with my gems I can just have this locally :)

**Comment by lislis** [comment]
Hmm, I think this might lead to troubles. But I'm not sure. ping @carpodaster

**Comment by carpodaster** [comment]
@alexwllms Are you using rvm or rbenv or something like that? The repo should automatically create a isolated gemset for rvm (don't know about rbenv). By using a gemset, we are sure not to interfer with any other gems installed on your system. Could you give that a try?

Judging by the version number, the updated Gemfile.lock doesn't contain any major upgrades so it *should* not break things but let's try to built it with the unmodified Gemfile.lock first.

**Comment by alexwllms** [comment]
I've removed the gemfile.lock changes and my build is still working, so perhaps put it down to a flaw in my setup. :)

**Comment by lislis** [comment]
@alexwllms amazing! +1

**Comment by anikalindtner** [comment]
MERGE!! someone!

**Comment by anikalindtner** [comment]
wheeeee!

**Comment by alicetragedy** [comment]
:heart_eyes:

**Pull request merged**
