### PR TITLE
Create 2015-07-15-Introducing-Team-Techylite

### PR DESCRIPTION
**Pull request by ghost**
Our blog post content.

### CODE REVIEW

**Comment by alicetragedy** [comment]
@Ressy77 I've made a couple of comments of things that should be changed before we can merge the pull request and publish your post. Let me know if you have any problems with changing that stuff, and I can help out. :+1:

**Comment by ghost** [comment]
@alicetragedy  How can I upload images to the img/blog/2015 folder. Can't seem to figure it out. Kindly help.
Also, I had already uploaded our images to a github issue- https://github.com/rails-girls-summer-of-code/summer-of-code/issues/98
Will that also work?

**Comment by alicetragedy** [comment]
@Ressy77 some of the other teams have "forked" our repo, allowing them to have a copy of the repo locally and to add some files to the `img` folder. However I think in your case, the file was added on GitHub directly (as per our instructions, which are outdated and need updating!) – so don't worry about it, I will take care of changing it for you after we've merged :) Unfortunately, though linking the image from an issue will work (as in, it will show), should the issue or repo you uploaded the images to be deleted, there will be a broken link in the blog post – this is why we try to have all used images in our repo directly, so we have control over them. But as I said – it's our mistake, so don't worry about it.

If you could just add the image credits still (or post here the names of the people the image should be credited to and/or where you found the image), I'll be able to merge after that. 

Also, if you are interested in reading up about forking a repo (you will be doing it that way for your other post at the end of the summer) here is some information about it: https://help.github.com/articles/fork-a-repo/

thank you!

**Comment by ghost** [comment]
Thank you @alicetragedy . I will fork the repo next time :-)
I got the first two images online on Google Images.
 I own the copy of our team photo.

**Comment by alicetragedy** [comment]
@Ressy77 yay, your pull request has been merged! :tada: 
We'll post the link soon. Congratulations on your first blog post! :confetti_ball: :sparkles:

**Pull request merged**
