### PR TITLE
add blog post for support from companies

### PR DESCRIPTION
**Pull request by alicetragedy**
feel free to make suggestions about the content eg. 
- naming companies
- is the coaching company paragraph understandable?
- making the coaching company bit shorter?

Also: before merging, we need to decide on a date for publishing this, and it needs to be moved out of the drafts folder into the posts folder.

### CODE REVIEW

**Comment by alicetragedy** [comment]
@anikalindtner @sareg0

**Comment by anikalindtner** [comment]
really cool, thanks for getting this done <3 

i'd love it if we could add some pictures! wdyt?

**Comment by alicetragedy** [comment]
yes, pictures would indeed be great, as it's such a long blog post.. 
Do we have anything we can use from the previous years?

**Comment by anikalindtner** [comment]
we do have some pictures on our fb-site (maybe a screenshot from last year's coaching companies map?) https://www.facebook.com/pages/Rails-Girls-Summer-of-Code/620914904656191 
and also here from the sponsor packages: http://railsgirlssummerofcode.org/blog/packages/ that might be interesting for sponsors?

**Comment by alicetragedy** [comment]
great! I'll scan through those later today, I'm sure I can find something (and I guess we don't need such hi-res for the blog post, so anything on facebook is fine). and I am TOTALLY using that photo of you and Floor, it's basically the whole RGSoC awesomeness summed up in four photos - I love it. :heart:

**Pull request merged**
