### PR TITLE
Mobile scrolling

### PR DESCRIPTION
**Pull request by claucece**
This pull request fixes issue #175 (navigation glitch on mobile). There is, though, still an issue regarding menu size on mobile.

### CODE REVIEW

**Comment by alicetragedy** [comment]
hey @claucece, I've taken a look at this, and it still doesn't scroll properly for me. I've tested it locally and on a mobile device (iPhone) and I can't scroll further than the last list item of "students". I can investigate a little bit on my end to see what solution I can come up with, but could you still try and see if you can get it to work?

**Comment by claucece** [comment]
Yes! that is the new bug I found.. it was introduced when 'home' was added. I'll keep looking at it.

**Comment by alicetragedy** [comment]
@claucece did you have any time to get this working? Or is there anything I can do to help?

**Comment by claucece** [comment]
@alicetragedy Yes.. but it gets fixed for some mobiles and for others don't. It is quite weird. Scrolling is fixed but it is like height does not really apply 'auto'. Have you investigate it?

**Comment by claucece** [comment]
Update: seems like the issue is due to 'position:fixed'

**Comment by alicetragedy** [comment]
hey @claucece, no I didn't have time to look into it at all this week. I tried a couple of things last week, but they did not resolve anything. :(

**Comment by claucece** [comment]
@alicetragedy It is soo weird. I think it is because of fixed position. Maybe this will help? http://stackoverflow.com/questions/10154250/scroll-part-of-content-in-fixed-position-container

**Comment by alicetragedy** [comment]
@claucece yeah, it's super weird :/ I don't think I will have any time to look at this until Monday at least, do you want to drop this issue? I don't want it to be too annoying or frustrating for you, but of course I'm happy if you keep looking into it.

**Comment by alicetragedy** [comment]
hey @claucece, would you still have time to look over and fix this issue over the next week? Please let me know by Friday (September 30th, 12:00 UTC) if not, so that I can hand this over to someone else to look at. Thanks!

**Comment by mkalininait** [comment]
Issue #175 is [fixed](https://github.com/rails-girls-summer-of-code/summer-of-code/commit/3a4e5944fe4fd755665e01f9917b272075b907ff). Can we close this PR?

**Pull request closed without merging**
