### PR TITLE
Create TeamTessie Introductory Blog Post

### PR DESCRIPTION
**Pull request by ShellyCoen**

### CODE REVIEW

**Comment by ShellyCoen** [comment]
@alicetragedy I used "git push" with the post (with proper extension) and it pushed it to gh-pages.  

Aaron is helping me with this otherwise, let me know if I have destroyed everything though :D

**Comment by alicetragedy** [comment]
@ShellyCoen no worries :) Let me know which way to fix it you found, there are several. I'd suggest always pushing the commits to "your" branch (`patch-1`), that way it gets added automatically to your PR. You could make the extension change here again, and we'll just close the other "accidental" PR – I think that's the easiest – but just ping me whenever you've fixed it "The Aaron Way". :+1:

**Comment by ShellyCoen** [comment]
It appears I tried to do things in a far more complicated way than necessary. :D

**Comment by alicetragedy** [comment]
@ShellyCoen it happens to the best of us. I have one more tiny request and then you are good to go.. we are trying to keep all the images in one place (in the `img` folder). if you look at that folder's structure, it's been arranged by year – do you think you could drop the group photo in there, and call it something rememberable (we use the structure `blog-post-name-image`)? It would be :+1: :+1: :+1: 
And then link to it in your blog post? the link will be something like `/img/blog/2015/your-image-name.jpg` and you can take any one of our blog posts with images for reference. Using html is okay too :)
Please let me know if you have any trouble, or if it's confusing. I promise we'll update the 'guide' so it will be easier on Halloween for your second blog post :dancers:

**Comment by ShellyCoen** [comment]
Could you please help me with "dropping it in" to that folder? I don't understand how to do that when I have no write access to the folder

**Pull request merged**
