### PR TITLE
updates to applications open blog post

### PR DESCRIPTION
**Pull request by sareg0**
These are the updates suggested for the 'applications opening' blog post.

### CODE REVIEW

**Comment by sareg0** [comment]
@alicetragedy wdyt? Can I merge?
I have something new I would like to PR. I'll merge you if you merge me :D

**Comment by alicetragedy** [comment]
I misunderstood yesterday that you were going to work on the crowdfunding post - told Anika I would do it. Anyway I didn't have much time for it today so thanks for doing this! :+1: 
Also, in the future can you do the separate blog-posts on separate branches? (aka send separate pull requests) that way we can edit / give feedback on the posts one by one and merging them as we go, instead of waiting for everything to be edited to merge! It doesn't really make a huge difference actually, but still. :sparkles:

**Comment by anikalindtner** [comment]
@alicetragedy aww sorry, totally slipped my mind! Can you share your ideas and we can then do a blog post out of both your inputs? <3

**Comment by alicetragedy** [comment]
haha, nooooo! no problem. I think that other than the feedback I gave up there, it's perfect and ready to go. And since we have a few upcoming blog posts half-ready to announce stuff, if the crowdfunding campaign is ready to be opened I think we should post this asap.

**Comment by sareg0** [comment]
No, you're right. Putting them on branches does make a huge lot of sense, and I'll do that in future.
Okay, just making the edits.

**Comment by alicetragedy** [comment]
oh and maybe you also want to add your name and twitter handle (or the RailsGirlsSoC handle) in the finished post, @sareg0 ?

**Comment by sareg0** [comment]
Wow, please see the final two files above for the 'real updates'... I kind of miffed up my commits a bit, but hopefully it's not too confusing.

**Comment by alicetragedy** [comment]
looks good to me!!! :+1:

**Comment by alicetragedy** [comment]
hahahha sorry... but that's the last change, I promise! :heart:

**Comment by sareg0** [comment]
@alicetragedy I am crossing my fingers ;)

**Comment by alicetragedy** [comment]
yayyyyy! merging!

**Comment by sareg0** [comment]
schweeet! Thank you @alicetragedy

**Pull request merged**
