### PR TITLE
add defunct faq text to guidelines

### PR DESCRIPTION
**Pull request by sareg0**
This is where I input the now defunkt FAQ text into the guidelines.

Old text here
https://github.com/rails-girls-summer-of-code/summer-of-code/issues/19

Please review, and make comments. Would love to get the baby merged asap

### CODE REVIEW

**Comment by sareg0** [comment]
thanks @alicetragedy for the title edit ;)

**Comment by alicetragedy** [comment]
dancing_81ce46_349289

**Comment by sareg0** [comment]
so many spelling mistakes... all around!

http://38.media.tumblr.com/ec7a7d7d4a2fb8ae5996d509928c3a85/tumblr_mwkm3u1SJ61sp4nfqo1_500.gif

**Comment by alicetragedy** [comment]
@sareg0 whenever you make the changes we're good to go and can merge this baby! :tada:

**Pull request merged**
