### PR TITLE
Fix minor grammar error

### PR DESCRIPTION
**Pull request by emkosz**

### CODE REVIEW

**Comment by emkosz** [comment]
It's a small grammar error that a friend of us pointed out.

**Comment by alicetragedy** [comment]
@emkosz true – I noticed when I read it, and completely forgot about it.. thanks for fixing!

**Comment by emkosz** [comment]
Awesome, is it possible to merge? @alicetragedy

**Comment by alicetragedy** [comment]
@emkosz done! I was just checking it out locally first since there was a merge conflict. :tada:

**Comment by emkosz** [comment]
Perfect! Thanks :) @alicetragedy 
Not sure if anyone else get the same, but I get a warning when I push to this repo:

screen shot 2015-09-30 at 12 14 11 pm

**Comment by alicetragedy** [comment]
@emkosz I don't – but thanks for letting us know, I will investigate further :)

**Comment by emkosz** [comment]
@alicetragedy Thanks :+1:

**Pull request merged**
