### PR TITLE
Add Fanxhe introduction post

### PR DESCRIPTION
**Pull request by fanxhe-pair**
This is our introduction post. Ready to review.

### CODE REVIEW

**Comment by alicetragedy** [comment]
hey @fanxhe-pair, thank you for the pull request! Everything is good for the post and it's almost ready to be published. All we need is for you to add image credits to all the images (eg. credit to who made the logo and the pictures, and also to where you found, for example, the GIFs). This is important information! Thanks in advance :) Looking forward to seeing your post on our blog! :sparkles:

**Comment by fanxhe-pair** [comment]
@alicetragedy We just pushed those changes :smile_cat:

**Comment by fanxhe-pair** [comment]
@alicetragedy It is ready! :thumbsup: :clap:

**Comment by fanxhe-pair** [comment]
@alicetragedy: it is ready! :clap: :+1:

**Comment by alicetragedy** [comment]
Great!!! congratulations on your first successful pull request on `summer-of-code` @fanxhe-pair! :sparkles:

**Comment by fanxhe-pair** [comment]
Thank You @alicetragedy =)

**Comment by joiggama** [comment]
Congrats @fanxhe-pair @anxhe @freewomancode :tada: :balloon:

**Pull request merged**
