### PR TITLE
Introducing Team The Tremors

### PR DESCRIPTION
**Pull request by Mercy-Nekesa**

### CODE REVIEW

**Comment by alicetragedy** [comment]
great @Mercy-Nekesa – thank you for the blog post! We just need an image credit and then we're ready to merge. Please add it whenever you can! :sparkles:

**Comment by Mercy-Nekesa** [comment]
Hi Laura,
Sorry for the late reply. During the weekend, we had internet access issues
all over the City due to President Obama's visit to Kenya. But I am adding
an image credit as requested.

Thank you

On Sat, Jul 25, 2015 at 7:39 PM, Laura notifications@github.com wrote:

> Merged #110
> https://github.com/rails-girls-summer-of-code/summer-of-code/pull/110.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/pull/110#event-365241883
> .

## 

Warm Regards,
Mercy Nekesa

**Comment by alicetragedy** [comment]
That's no problem @Mercy-Nekesa – don't worry about it.
Credit has been added in https://github.com/rails-girls-summer-of-code/summer-of-code/commit/128eb4f6f4f2d4495726bbb11aab7a72fd37893c

**Comment by Mercy-Nekesa** [comment]
Thanks again Laura

On Mon, Jul 27, 2015 at 5:19 AM, Laura notifications@github.com wrote:

> That's no problem @Mercy-Nekesa https://github.com/Mercy-Nekesa – don't
> worry about it.
> Credit has been added in 128eb4f
> https://github.com/rails-girls-summer-of-code/summer-of-code/commit/128eb4f6f4f2d4495726bbb11aab7a72fd37893c
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/pull/110#issuecomment-125184594
> .

## 

Warm Regards,
Mercy Nekesa

**Pull request merged**
