### PR TITLE
Create 2015-07-16-Introducing-Team-GirlsCodersWarsaw.md

### PR DESCRIPTION
**Pull request by Czarrrna**
Is it working? ;)

### CODE REVIEW

**Comment by alicetragedy** [comment]
Perfect!!!!! :sparkles: 
I will merge it later today. Congratulations on your first successful pull request on the summer-of-code repo!

**Comment by Czarrrna** [comment]
The second one actually ;) But thanks :)

**Comment by alicetragedy** [comment]
True! the second one :) :dancers: :tada:

**Comment by Czarrrna** [comment]
@alicetragedy I noticed that links don't work. Could you fix it, please?

**Comment by alicetragedy** [comment]
@Czarrrna can you point me to which links you mean? I've just tried all three of them, and they seem to work fine. :)
I've just added the images to our folder and pushed a new commit, maybe you checked out the post right at that time. Please tell a look at it again and let me know if something still doesn't work!

**Comment by Czarrrna** [comment]
@alicetragedy 
There shouldn't be a space:
 [CodeQuest](codequest.com)
 [.Class workshops](http://dotclass.org)
I mean the space between brackets.

**Comment by Czarrrna** [comment]
it works here, but not on the blog :(
I can see the brackets in the post on the blog.

**Comment by alicetragedy** [comment]
@Czarrrna ah, there! thanks for letting me know :+1: 
I've just fixed it. It should work fine now :)

**Comment by Czarrrna** [comment]
@alicetragedy Yeah, now they work fine! Thank you, Laura! :)

**Comment by alicetragedy** [comment]
No problem @Czarrrna! By the way, when you notice some small mistakes like that, you can definitely make the changes on your fork and make another pull request, if you want to practice ;) We're always happy about improvements and contributions to the site or the blog!

**Pull request merged**
