### PR TITLE
Guide improvements

### PR DESCRIPTION
**Pull request by alicetragedy**
small improvements:
- improved the eligibility criteria wording
- added a line about the submitted application not being editable
- updated deadlines and added exact time of applications closing to avoid misunderstandings

### CODE REVIEW

**Comment by mkalininait** [comment]
@alicetragedy Something related. Today we've got two support requests of this sort:

"Hi support team! I'm currently trying to save a draft of my application but it deletes everything every time I press the "Save as draft" button. Is there a bug or is it possibly because me and my pair are both writing our applications at the same time?"

My answer was: "Theoretically, filling out an application simultaneously should be possible, but in practice there might be an undocumented bug somewhere there. We had 1 or 2 application glitches last year, which might or might not have been the result of simultaneous editing. Thus, I’d recommend not to do it if possible."

So I wonder if we should add this to the guide. WDYT?

**Comment by alicetragedy** [comment]
@mkalininait I think we could definitely add it to the guide, though I also think that advice of this kind might also be better suited in the form itself and/or in the help pages. Anyway, if you see a use for it in the guide we can add it! Would you like to pull in this branch and do it yourself today, or want me to take care of it? I'm out most of the day but will be back around 4pm and can make the changes then 👍

**Comment by mkalininait** [comment]
@alicetragedy I have some tasks on my list, but I can take this one afterwards. Unless you have time before that.

**Comment by alicetragedy** [comment]
@mkalininait no worries, you have a lot on your plate right now — I can take a look at it tonight.

**Comment by alicetragedy** [comment]
@mkalininait I've added the line needed using a similar wording to yours — feel free to merge this if you're satisfied with it. I'd also suggest adding something like that to the help pages :)

**Pull request merged**
