### PR TITLE
Create 2015-09-18-the-end-of-a-wonderful-summer.md

### PR DESCRIPTION
**Pull request by BubetoManolova**
RGSoC 2015 - Team Rails Girls Enthusiasts

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hi @BubetoManolova, sorry for reviewing this so late. I've added minor comments of things that need changing.
Also, all the image links are broken – can you make sure that the images are in your local `img/blog/2015` folder and that you add them to this pull request? 
please let me know if you need any help with that. thank you!

**Comment by alicetragedy** [comment]
@BubetoManolova don't worry, it happens. 
I've merged the PR with the photos now – feel free to change the links and fix the other errors, I can take a look at it when you are done. Thank you for getting back to me first thing this morning :)

**Comment by BubetoManolova** [comment]
@alicetragedy  I think it's done :) But please take a look when you can :)

**Comment by alicetragedy** [comment]
awesome work @BubetoManolova – thank you for your changes! :tada: :confetti_ball:

**Comment by BubetoManolova** [comment]
:+1:

**Pull request merged**
