### PR TITLE
Rubyherzlein blogpost

### PR DESCRIPTION
**Pull request by nynnejc**

### CODE REVIEW

**Comment by alicetragedy** [comment]
awesome!!! :tada: I'll review and then merge when it's time. Thank you @nynnejc!

**Comment by alicetragedy** [comment]
@nynnejc it seems like there is some trouble with the images (some of them are tilted and I don't know why). I'm taking care of it and will see what the problem is and try to fix it. Just wanted to let you know in case you don't know why the post isn't published yet! Thank you for your patience. 
Also, could you let me know the credit for the first two pictures (eurucamp) and the last two? I'd just need to know where the images came from/where you found them, and I will add it to the file. thank you! :sparkles:

**Comment by nynnejc** [comment]
Oh I'm so sorry about the images. I'll add image credit to the text. Thanks so much for the help!

**Comment by alicetragedy** [comment]
don't worry about it! if you are adding the image credits to the text directly with another pull request, please pull the changes from the repo – I've moved the blog post temporarily to the `_drafts` folder, so please add the changes there directly. Otherwise you can also post the image credit info in this as a comment, and I will add it!

**Comment by nynnejc** [comment]
Oh great. The very first image should be credited to Bitcrowd and every other image should be credited to Team rubyherzlein :)

**Comment by nynnejc** [comment]
Thanks for the help!

**Comment by alicetragedy** [comment]
No problem! I'll make sure to add that info. thank you for getting back to me so fast! :+1:

**Pull request merged**
