### PR TITLE
Updating the coaching company guide

### PR DESCRIPTION
**Pull request by ghost**
Anika and me worked on some changes to the coaching company guide

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hey @Nattivolk, there are quite a lot of conflicts with the current coaching company guide, as some changes to it have already been made in the last week. Could you close this pull request, pull in the last changes, and base your new changes on the way the CC guide is now structured? (eg. "What coaching companies don't do" is now a subset of "What is a coaching company"). 
For example I really like those links to blog posts by companies and think they should definitely be in there :) thanks!!

**Comment by ghost** [comment]
Sorry, I thought I was up to date. 
Which branch is the working branch? gh-pages?
Regarding the structure I pulled all the changes from a google docs, @anikalindtner and me were working on. Not sure, what should be the latest version now?

**Comment by alicetragedy** [comment]
@Nattivolk yes, it's `gh-pages`. maybe you can try:

```
git checkout gh-pages
git pull 
```

and see if you see that it's pulling any changes related to the CC guide. for example, in the diff the list of links for the different sections at the top looks different, so I assumed you might have been working on an older version somehow.

**Comment by ghost** [comment]
Closed the pull request for now, will have a look later during lunch time. Might ping you, if you are available later :)

**Comment by alicetragedy** [comment]
sorry about that — I know it's super annoying, but I couldn't really see a better solution. :see_no_evil: 
you can ping me once you've updated, and I can quickly review your new PR before merging. thanks so much for your help!

**Pull request closed without merging**
