### PR TITLE
Projects guide update

### PR DESCRIPTION
**Pull request by anasofiapinho**
Update the projects guide to include the extra week for project submissions.

### CODE REVIEW

**Comment by anasofiapinho** [comment]
Hey @anikalindtner, so you said you wanted to close submissions in your time, so that means that it's your 17:59:59 CET, so it will be then 16:59:59 UTC / GMT. Right?

**Comment by anasofiapinho** [comment]
Thank you @carpodaster ! Tiago is licking himself after all the treats!
I included the date as well. Now I just need to know about the time so that you can publish!

**Comment by anasofiapinho** [comment]
Done! @carpodaster and @anikalindtner 
Can we merge this?

**Comment by anikalindtner** [comment]
@anasofiapinho I'd assume that since the app only knows UTC, the date should be 17:59:59 UTC

**Comment by anasofiapinho** [comment]
Yes @anikalindtner ! Laura was the one who said this time on our hangout last week and she just replied on slack saying that it was UTC.

**Pull request merged**
