### PR TITLE
add blog post for application wrap-up

### PR DESCRIPTION
**Pull request by alicetragedy**
brief blog post about application wrap-up with a few stats and timeline for the upcoming month

### CODE REVIEW

**Comment by sareg0** [comment]
excellent! I guess I just have those changes I mentioned above to add, and then I'm happy to merge the pull request.

**Comment by alicetragedy** [comment]
thank you! made the changes @sareg0. I completely overlooked that :D

**Comment by sareg0** [comment]
Merrrrrrged!!! Lemme know if I can delete that branch now or if you have any additions to make before we promote it tomorrow x

**Comment by alicetragedy** [comment]
@sareg0 no, it's perfect – thanks for merging :tada:

**Pull request merged**
