### PR TITLE
Re #282 Improve mobile experience

### PR DESCRIPTION
**Pull request by katrin-k**
This PR improves the following list items from issue #282 
- Mobile-friendly image for Application Guide
- Remove megaphone in footer on mobile
- Improve look of coaching company page
- Improve look of conferences list on students/conferences
- Improve font size for headings h1, h2, h3

### CODE REVIEW

**Comment by alicetragedy** [comment]
This looks good, except for the conference table, which looks really weird on mobile (at least on mine). I can try to take a better look later this afternoon or on Wednesday, or cherry-pick the currently working commits and leave the rest (conference-table) for later :)
Thanks for your work @katrin-k. 🎉

**Comment by katrin-k** [comment]
Hmm… I did only double-check the list of conferences using browser dev tools. 
@alicetragedy did you find some time for checking? Or could you otherwise add a screenshot?

**Comment by alicetragedy** [comment]
@katrin-k this is what it looks like on iphone 6 in the browser:
img_2329-1

I haven't investigated but it seemed like the most sensible way to solve this was to talk with you after you're back. my browser tools on the laptop also lied and made it look ok :/

**Comment by katrin-k** [comment]
oh dear… From a first guess, I'd say `flex: column;` and Iphone 6's Safari(?) don't like each other. To achieve the same, in the small screen media query one could also use 

```
flex-direction: row;
flex-wrap: wrap;
```

for the container and 

```
flex: 1 1 100%;
```

on the flex children. (I hope, I remember this correctly and that's the full code…)

**Comment by alicetragedy** [comment]
@katrin-k if that's okay with you, I'll try to get this working so we can merge your PR, hoping to take a look today <3

**Review by alicetragedy — APPROVED** [review]
I've fixed the css based on your suggestions and it seems to be working seamlessly now, so I've pushed the new changes. Since everything else in the PR looks good, I think we can merge it :)

**Pull request merged**
