### PR TITLE
Add Team Tessie final post and images

### PR DESCRIPTION
**Pull request by tamacodechi**

### CODE REVIEW

**Comment by alicetragedy** [comment]
thank you for the PR @Althaire! It almost all looks clear on my end and I'm almost ready to merge .. I've just noticed that the stats have been added/linked to twice, whereas the second image added hasn't been linked in the post at all. Could you fix that? (if you're not using the second image, you can happily delete it)
After that I'm ready to MERGE ALL THE THINGS! :space_invader:

**Comment by tamacodechi** [comment]
Thank you for spotting that @alicetragedy! I accidentally linked to the same image twice instead of linked to our two separate images. Should be fixed now :)

**Comment by alicetragedy** [comment]
purrfect! :cat: that's just what I thought.

**Comment by cypher** [comment]
:thumbsup: (I found Internet!)

**Pull request merged**
