### PR TITLE
fixes => Clean up img folder Issue #359

### PR DESCRIPTION
**Pull request by chantal66**
- moves files to a new directory called 'unused' directory after checking for usage in file tree.
- moves ajax-loader.gif to a more appropriate directory. 
- there are 6 images that they are used but not quite sure where they could belong. 
- updates path for ajax-loader.gif

### CODE REVIEW

**Review by alicetragedy — CHANGES_REQUESTED** [review]
Hi @chantal66, thanks so much for this! It looks good. There's just a minor thing — since you've moved the `ajax-loader` to a different subfolder, you'll want to update the link for it in the code so that it can still be found. That would be `team.scss`. After that, I believe we're ready to go 🎉

**Comment by chantal66** [comment]
Oh! I thought I updated all relevant paths... I’ll check.

Thank you for the feedback 

Chantal

**Comment by chantal66** [comment]
Hi @alicetragedy 
this is what I found on team.scss where sprites is the new folder... does this looks good to you? or maybe I'm missing something... please let me know.. 
```
.page-team article.is-loading {
  background-image: url('../../../img/sprites/ajax-loader.gif');
  background-repeat: no-repeat;
  background-position: center;
}
```

**Comment by alicetragedy** [comment]
@chantal66 Could you double-check that these local changes you have have been committed and/or pushed to your pull request? If I click on “Files changed” in this PR (in the Github interface), I don't see any changes to the `team.scss` file, just to the image files. I could be wrong, but it _seems_ like you might have made the changes locally and either not committed them, or committed them but not pushed them to your branch to update the PR. Please check if that's the case — if yes, you should be able to update your PR (let me know if you need help). If not, we can look into this together and see what the issue might be 🤔  Thanks so much in advance for this!

**Comment by chantal66** [comment]
sorry for the delay.. path updated for team.scss

**Review by alicetragedy — APPROVED** [review]

**Comment by alicetragedy** [comment]
This is great @chantal66 — thank you so much for making the requested change. 
Looks like we're all set and ready to go — I'm going to merge this. 🎉

**Pull request merged**
