### PR TITLE
Create 2015-july-28-introducing-team-codebenders.md

### PR DESCRIPTION
**Pull request by meghaarora42**
Blog post by Team CodeBenders!

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hi @meghaarora42 – thank you for your great blog post! :sparkles: 
Here are a couple of things that are missing/that need changing:
- add date to permalink (eg. `blog/2015-07-28-your-post-title`)
- add image credit to image (see other blog posts for an example)
- add your image to the `img/blog/2015` folder in the repo, so it can be linked directly, as mentioned [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/README.md). 

If you have any questions or are confused about anything, please let me know. 
It might be that you created the file on github.com directly instead of forking the repo – if you did it that way, just ping me and I will add the image to our folder myself after merging/publishing your post. 
thanks in advance!

**Comment by meghaarora42** [comment]
I have made all the changes and created another pull request! Let me know in case we missed anything. Thanks! :)

**Comment by alicetragedy** [comment]
@meghaarora42 Super, thanks for doing this so quickly! I will then close this one.

**Comment by meghaarora42** [comment]
:)

**Comment by meghaarora42** [comment]
Our post will be up today right?

**Comment by alicetragedy** [comment]
@meghaarora42 yes, it will. You will get a notification once we publish, and we will tweet about it, too.

**Comment by meghaarora42** [comment]
Perfect! Thanks for the information. :)

**Pull request closed without merging**
