### PR TITLE
dates on landing page updated

### PR DESCRIPTION
**Pull request by linberg**

### CODE REVIEW

**Comment by alicetragedy** [comment]
I will review this tomorrow if that's okay @linberg but yeah, I would suggest removing the year for now (you can add an extra commit to this PR that removes the year, without creating a fresh PR instead!)

**Comment by alicetragedy** [comment]
Hej @linberg, looks good to me! 👍 
I've realised that the dates can actually seem pretty confusing for Americans because of conflicting date formats, so I was thinking maybe we could replace the month numbers with month abbreviations. I've tried it locally (e.g. 20 Nov–31 Jan) and it works at all breakpoints without breaking for smaller screen sizes. What do you think? Should we change it? 
Alternatively, we can merge this PR and I can make the changes to the months later. Let me know what works best :) (I would add changes on top of your PR but I can't because it's a branch in your own repo)

**Comment by linberg** [comment]
Huhu @alicetragedy, that sounds good - least amount of confusion this way. I'll make those changes now!

**Review by alicetragedy — APPROVED** [review]
yay!! awesome work 🙌

**Pull request merged**
