### PR TITLE
Team Delta Quadrant Wrap Up Post

### PR DESCRIPTION
**Pull request by Realtin**
✨

### CODE REVIEW

**Comment by alicetragedy** [comment]
thank you @Realtin! I will review this tomorrow, as early as I can. \o/

**Comment by alicetragedy** [comment]
Awesome! nothing needs changing. I'll merge as soon as possible! ✨💖

**Comment by Realtin** [comment]
Great! 🐳

**Comment by alicetragedy** [comment]
@Realtin I just realised that the images don't have a credit. Could you post here where you got them from so we can add credits to the post? Thank you! :sparkles:

**Comment by Realtin** [comment]
das erste von hier : http://mistresscara1000.tumblr.com/post/61292922924/our-favourite-captains-expressions-can-sum-up-any

das ganz am ende: http://i-amarobot.tumblr.com/post/117556937146

**Comment by alicetragedy** [comment]
:+1:

**Pull request merged**
