### PR TITLE
The second Alster Hamburger blog post

### PR DESCRIPTION
**Pull request by ankonym**
Hello dear RGSoC ladies, 

here's our finished blog post for next Wednesday. 
We're a bit early because we'll be at the Polymer Summit in Amsterdam on Monday and Tuesday but hopefully it's good to go! :) 

Have a nice weekend, 
Anke

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hi @ankonym – this looks good. I will merge it tomorrow and tweet about it, thank you for getting in done on time :)
Some of the images are a bit pixelated, unfortunately the images are by default shown with full-width. let me know if you think we should make them smaller. Enjoy the last few hours of the Polymer Summit!

**Comment by ankonym** [comment]
Hi Laura,

Sorry for the late response (strangely, the Polymer (developer! Google!)
summit had only extremely flaky WiFi! :-D).

I thought all our images are maximum 600px wide? Or will the smaller ones
get stretched to that width and then look pixelated? I made the ones that
are higher than wide a bit smaller so they don't turn out huge on the blog.
Is there a way of keeping them at that size?

Sorry for being confused. :)

All the best from Amsterdam,
Anke
Am 15.09.2015 3:04 nachm. schrieb "Laura" notifications@github.com:

**Comment by alicetragedy** [comment]
@ankonym all it means is that all the pictures will be stretched to fit the width of the blog (unless they are set next to each other, like the two from the lightning talks). It doesn't look too bad but I just wanted to warn you, in case you have wider versions of the pictures and want to replace them :) We can also do that after the merge, when you are back.
Also, it's possible to run the command `jekyll serve --watch` from the terminal (I don't know if you have a working Ruby environment, and if you've used jekyll before, but it can be installed without too much trouble if I remember correctly) to always see what the site would look like (`localhost:4000/blog/` in the browser).

**Comment by ankonym** [comment]
Ok, I have changed one image (added a wider one) and removed another one (we had quite a few anyway), and adjusted the blog post accordingly. :) I think the animated gif will be okay even if stretched. 

I'll go learn more about jekyll now but hope that the blog post is now good to go!

**Comment by ankonym** [comment]
I was wondering if you still need anything from us? Or is the blog post okay to merge? :)

**Comment by alicetragedy** [comment]
all merged! :+1: thanks for your great work @ankonym & @ayajaff!

**Comment by ankonym** [comment]
Yay! :) Thank you!

**Pull request merged**
