### PR TITLE
Blog post #1 for team Alster Hamburgers

### PR DESCRIPTION
**Pull request by ankonym**
This is our first blog post as well as its images

### CODE REVIEW

**Comment by adamniedzielski** [comment]
I like it :+1: Great piece of writing

**Comment by alicetragedy** [comment]
great post @ankonym! I will merge and publish the pull request on Monday. :tada:

**Comment by ankonym** [comment]
Thank you @adamniedzielski and @alicetragedy ! :)

**Comment by ankonym** [comment]
@alicetragedy For some reason, half of the links are showing up wrongly formatted on the blog while some are as they should be? In the preview, everything was fine and I actually don't see the error in the code - how can I adjust this?

**Comment by alicetragedy** [comment]
It's fixed! the problem was that there were in some cases spaces between the square brackets and the round brackets. So something like 
`[link text here] (www.url.com)` 
instead of 
`[link text here](www.url.com)`

really a tiny mistake which I also didn't notice :)

**Pull request merged**
