### PR TITLE
Team Melbourne Blog

### PR DESCRIPTION
**Pull request by cyberkoi**
We decided to get the post done early!

### CODE REVIEW

**Comment by alicetragedy** [comment]
hey team, great work! :+1:  As we have a blog post scheduled for tomorrow and we'd like to more or less stick to the schedule, I'd like to move your post/merge this pull request on Sunday July 12th. I'll make the changes in the editorial calendar now!

**Comment by alicetragedy** [comment]
You can add all future commits to this pull request – I will merge it on Sunday. :tada:

**Comment by cyberkoi** [comment]
@alicetragedy Sure! Date changed, image added, thank you! Anything else? :-)

**Comment by alicetragedy** [comment]
@snjqi188 wheee, thank you! could you save the image in our `img/blog/2015` folder instead of Google Drive (so that if the image gets deleted somehow we don't have broken links in the blog)? If you have problems with that let me know :) that will be my last request, after that you're good to go! \o/

**Pull request merged**
