### PR TITLE
remove sidebar hopefully from everywhere

### PR DESCRIPTION
**Pull request by anikalindtner**
and added the illustrations

### CODE REVIEW

**Comment by anikalindtner** [comment]
@alicetragedy does this look correct to you? tried my best to not #yolodoallthethings :sparkles:

**Comment by alicetragedy** [comment]
@anikalindtner I will take a look later tonight/tomorrow. I've run it locally, but there's a few problems with the illustration as far as I can see (it's way too wide, comes off the page and isn't responsive). I'll check when I can! :+1:

**Comment by anikalindtner** [comment]
@alicetragedy weird. i actually created a class for it with whitespace added.

**Comment by alicetragedy** [comment]
it needs to be moved into another stylesheet. will double-check :see_no_evil:

**Comment by alicetragedy** [comment]
just moving the code like I commented above should work. can you make that change and ping me then? (or merge after running it locally and checking that it looks the way you want it to look)

**Comment by anikalindtner** [comment]
@alicetragedy ping! :)

**Pull request merged**
